// Generated by Apple Swift version 2.3 (swiftlang-800.10.12 clang-800.0.38)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import ObjectiveC;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class UIColor;
@class NSCoder;
@class ClientConnector;
@class UIImage;

SWIFT_CLASS("_TtC17MobileCapture2SDK22CPCameraViewController")
@interface CPCameraViewController : UIViewController
@property (nonatomic) BOOL debugPrint;
@property (nonatomic) CGFloat insetHorizontal;
@property (nonatomic) CGFloat insetTop;
@property (nonatomic) CGFloat insetBottom;
@property (nonatomic) CGRect cropViewFrame;
@property (nonatomic) BOOL cropViewDisableZoom;
@property (nonatomic) int32_t cropViewGapLeft;
@property (nonatomic) int32_t cropViewGapTop;
@property (nonatomic) int32_t cropViewGapRight;
@property (nonatomic) int32_t cropViewGapBottom;
@property (nonatomic) BOOL borderCornerIndicatorsVisible;
@property (nonatomic, strong) UIColor * _Nonnull borderCornerIndicatorsNoMatchColor;
@property (nonatomic, strong) UIColor * _Nonnull borderCornerIndicatorsMatchColor;
@property (nonatomic) BOOL showDetectedBoundaries;
@property (nonatomic, strong) UIColor * _Nonnull boundaryNoMatchColor;
@property (nonatomic, strong) UIColor * _Nonnull boundaryMatchColor;
@property (nonatomic, copy) void (^ _Nullable autoSnap)(void);
@property (nonatomic, copy) void (^ _Nullable cameraStopped)(void);
@property (nonatomic, copy) void (^ _Nullable cropStarted)(void);
@property (nonatomic, copy) void (^ _Nullable noAccessToCamera)(void);
@property (nonatomic, copy) void (^ _Nullable pageDetected)(void);
@property (nonatomic, copy) void (^ _Nullable pageNotDetected)(void);
@property (nonatomic) BOOL takePictureSetsCropCorners;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)stopCamera;
- (void)startCamera;
- (void)flashOn:(BOOL)on;
- (void)startAppActivationCameraListener;
- (void)stopAppActivationCameraListener;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)didReceiveMemoryWarning;
- (void)takePicture:(void (^ _Nonnull)(BOOL foundPage))imageTaken;
- (void)showCrop;
- (void)hideAndClearCrop;
- (void)cropAndAddPage:(ClientConnector * _Nonnull)clientConnector;
- (void)addPage:(ClientConnector * _Nonnull)clientConnector;
- (void)importImage:(UIImage * _Nonnull)image finished:(void (^ _Nonnull)(void))finished;
- (void)resetBorderDetection;
@end

@class NSError;

SWIFT_CLASS("_TtC17MobileCapture2SDK7CPError")
@interface CPError : NSObject
@property (nonatomic, strong) NSError * _Nullable nsError;
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@class WebData;
@class NSURLAuthenticationChallenge;
@class NSURLCredential;
@class Notification;
@class FieldMessage;
@class FieldDefinition;
@class NSDictionary;

SWIFT_CLASS("_TtC17MobileCapture2SDK15ClientConnector")
@interface ClientConnector : NSObject
@property (nonatomic, strong) WebData * _Nullable webEntryData;
@property (nonatomic, readonly) BOOL startedFromWeb;
@property (nonatomic, copy) void (^ _Nullable sessionDidReceiveAuthenticationChallengeHandler)(NSURLAuthenticationChallenge * _Nonnull challenge, void (^ _Nonnull completionHandler)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable));
- (nonnull instancetype)initWithBackgroundIdentifier:(NSString * _Nonnull)backgroundIdentifier OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) BOOL debugNetRequest;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified deviceUniqueId;
@property (nonatomic, readonly, copy) NSString * _Nullable deviceToken;
- (void)registerDeviceToken:(NSString * _Nonnull)registrationToken;
@property (nonatomic, copy) void (^ _Nullable backgroundTransferCompletionHandler)(void);
- (void)registerDocumentTypeSelectedListener:(void (^ _Nonnull)(void))listener;
- (void)removeDocumentTypeSelectedListener;
- (void)registerPreUploadListener:(void (^ _Nonnull)(NSString * _Nonnull))listener;
- (void)removePreUploadListener;
- (void)registerProgressListener:(NSString * _Nonnull)key listener:(void (^ _Nonnull)(NSString * _Nonnull notificationUniqueId, float progress))listener;
- (void)removeProgressListener:(NSString * _Nonnull)key;
- (void)registerNotificationsFetchedListener:(NSString * _Nonnull)key listener:(void (^ _Nonnull)(NSArray<Notification *> * _Nonnull))listener;
- (void)removeNotificationsFetchedListener:(NSString * _Nonnull)key;
- (void)registerNotificationsChangedListener:(NSString * _Nonnull)key listener:(void (^ _Nonnull)(NSInteger badgeCount))listener;
- (void)removeNotificationsChangedListener:(NSString * _Nonnull)key;
@property (nonatomic, readonly) NSInteger selectedDocumentTypeIndex;
- (void)selectDocumentTypeIndex:(NSInteger)index finished:(void (^ _Nonnull)(CPError * _Nullable error))finished;
- (void)initFieldDefinitionsFromServer:(void (^ _Nonnull)(CPError * _Nullable error))finished;
- (void)updateFieldsAfterChange:(void (^ _Nonnull)(BOOL changed, CPError * _Nullable error, NSArray<FieldMessage *> * _Nullable fieldMessages))finished;
- (NSString * _Nonnull)createDocumentState:(BOOL)makeCurrent;
- (void)restoreDocumentState:(NSString * _Nonnull)documentStateUniqueId forNotificationUniqueId:(NSString * _Nonnull)forNotificationUniqueId;
- (void)switchToDocumentState:(NSString * _Nonnull)documentStateUniqueId;
- (void)removeDocumentState:(NSString * _Nonnull)documentStateUniqueId;
- (NSArray<FieldDefinition *> * _Nonnull)fieldDefinitionsForDocumentState:(NSString * _Nonnull)documentStateUniqueId documentTypeIndex:(NSInteger)documentTypeIndex includeHiddenFields:(BOOL)includeHiddenFields;
- (NSArray<NSString *> * _Nonnull)documentFieldNames:(NSString * _Nonnull)documentStateUniqueId;
- (NSString * _Nullable)documentFieldValue:(NSString * _Nonnull)documentStateUniqueId name:(NSString * _Nonnull)name;
- (void)documentSetFieldValue:(NSString * _Nonnull)documentStateUniqueId name:(NSString * _Nonnull)name value:(NSString * _Nullable)value;
- (void)addDocumentHiddenFieldName:(NSString * _Nonnull)documentStateUniqueId name:(NSString * _Nonnull)name;
- (void)removeDocumentHiddenFieldName:(NSString * _Nonnull)documentStateUniqueId name:(NSString * _Nonnull)name;
- (void)clearDocumentHiddenFieldNames:(NSString * _Nonnull)documentStateUniqueId;
- (NSInteger)documentNumberOfPages:(NSString * _Nonnull)documentStateUniqueId;
- (UIImage * _Nullable)documentPreviewPage:(NSString * _Nonnull)documentStateUniqueId index:(NSInteger)index;
- (UIImage * _Nullable)documentPageImageForUniqueId:(NSString * _Nonnull)documentStateUniqueId index:(NSInteger)index decryptionKey:(NSString * _Nonnull)decryptionKey;
- (NSInteger)documentTypeIndexForDocumentState:(NSString * _Nonnull)documentStateUniqueId;
- (NSString * _Nonnull)documentDisplayName:(NSString * _Nonnull)documentStateUniqueId;
- (NSString * _Nullable)documentCustomData:(NSString * _Nonnull)documentStateUniqueId;
- (void)setDocumentCustomData:(NSString * _Nonnull)documentStateUniqueId customData:(NSString * _Nonnull)customData;
- (void)setDocumentUploadConfigurationUniqueId:(NSString * _Nonnull)documentStateUniqueId uploadConfigurationUniqueId:(NSString * _Nonnull)uploadConfigurationUniqueId;
@property (nonatomic, readonly) NSInteger currentDocumentTypesCount;
- (NSString * _Nonnull)currentDocumentTypeName:(NSInteger)i;
- (NSString * _Nonnull)currentDocumentTypeDisplayName:(NSInteger)i;
- (NSInteger)currentDocumentTypeFieldDefinitionCount:(NSInteger)i;
- (FieldDefinition * _Nonnull)currentDocumentTypeFieldDefinitionNames:(NSInteger)documentTypeIndex fieldIndex:(NSInteger)fieldIndex;
@property (nonatomic, readonly, copy) NSString * _Nonnull currentDocumentStateUniqueId;
@property (nonatomic, readonly) BOOL currentDocumentStateIsNew;
@property (nonatomic, readonly, copy) NSString * _Nonnull selectedDocumentTypeName;
@property (nonatomic, readonly, copy) NSString * _Nonnull selectedDocumentTypeDisplayName;
@property (nonatomic, readonly) BOOL getSelectedDocumentTypeMetadataFromServer;
@property (nonatomic, readonly) BOOL getSelectedDocumentTypeValidateOnSubmit;
@property (nonatomic, copy) NSString * _Nullable selectedDocumentCustomData;
@property (nonatomic, readonly, copy) NSArray<FieldDefinition *> * _Nonnull selectedDocumentFieldDefinitions;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull selectedDocumentFieldNames;
- (NSString * _Nullable)selectedDocumentFieldValue:(NSString * _Nonnull)name;
- (void)selectedDocumentSetFieldValue:(NSString * _Nonnull)name value:(NSString * _Nullable)value;
@property (nonatomic, readonly) NSInteger selectedDocumentNumberOfPages;
- (UIImage * _Nonnull)selectedDocumentPreviewPage:(NSInteger)index;
- (UIImage * _Nullable)selectedDocumentPageImage:(NSInteger)index decryptionKey:(NSString * _Nonnull)decryptionKey;
- (void)selectedDocumentRemovePage:(NSInteger)index;
- (void)selectedDocumentRotatePage:(NSInteger)index;
- (void)selectedDocumentMovePage:(NSInteger)fromIndex toIndex:(NSInteger)toIndex;
@property (nonatomic, readonly, copy) NSArray<Notification *> * _Nonnull notifications;
- (Notification * _Nullable)notificationForUniqueId:(NSString * _Nonnull)uniqueId;
- (Notification * _Nullable)notificationForIndex:(NSInteger)index sortingValue:(NSString * _Nonnull)sortingValue;
- (Notification * _Nullable)notificationForIndex:(NSInteger)index sortingValue1:(NSString * _Nonnull)sortingValue1 sortingValue2:(NSString * _Nonnull)sortingValue2;
- (NSArray<Notification *> * _Nullable)notificationsForDocumentState:(NSString * _Nonnull)documentStateUniqueId;
- (void)removeNotification:(NSString * _Nonnull)notificationUniqueId;
- (NSInteger)getBadgeCount;
- (void)fetchMessages:(NSString * _Nonnull)documentStateUniqueId;
- (void)markMessageRead:(NSString * _Nonnull)messageUniqueId;
- (void)environmentURLForAccount:(NSString * _Nonnull)url loginName:(NSString * _Nonnull)loginName finished:(void (^ _Nonnull)(CPError * _Nullable error, NSString * _Nullable configurationURL, NSString * _Nullable authURL, NSString * _Nullable notificationRegisterDeviceURL))finished;
- (void)environmentURLForConfigurationUniqueId:(NSString * _Nonnull)url configurationUniqueId:(NSString * _Nonnull)configurationUniqueId finished:(void (^ _Nonnull)(CPError * _Nullable error, NSString * _Nullable configurationURL, NSString * _Nullable authURL, NSString * _Nullable notificationRegisterDeviceURL))finished;
- (void)authenticate:(NSString * _Nonnull)authURL loginName:(NSString * _Nonnull)loginName password:(NSString * _Nonnull)password finished:(void (^ _Nonnull)(CPError * _Nullable error, NSDictionary * _Nullable authResponseJSON))finished;
- (void)getAuthData:(void (^ _Nonnull)(NSString * _Nullable loginName, NSString * _Nullable password, BOOL stayLoggedIn))result;
- (void)storeAuthData:(NSString * _Nonnull)loginName password:(NSString * _Nonnull)password stayLoggedIn:(BOOL)stayLoggedIn;
- (void)clearAuthData;
- (BOOL)hasCachedDataForUser:(NSString * _Nonnull)username;
- (void)updateSession:(NSString * _Nullable)sessionId userIdentifier:(NSString * _Nullable)userIdentifier configurationUniqueId:(NSString * _Nullable)configurationUniqueId;
- (void)load:(NSString * _Nonnull)url finished:(void (^ _Nonnull)(CPError * _Nullable error, NSDictionary * _Nullable configurationResponseJSON))finished;
- (void)loadConfiguration:(NSString * _Nonnull)configurationUniqueId finished:(void (^ _Nonnull)(CPError * _Nullable error, NSArray<NSDictionary *> * _Nullable docTypesJSON))finished;
- (void)loadConfiguration:(NSString * _Nonnull)url configurationUniqueId:(NSString * _Nonnull)configurationUniqueId environmentFound:(void (^ _Nullable)(NSString * _Nullable notificationRegisterDeviceURL))environmentFound finished:(void (^ _Nonnull)(CPError * _Nullable error, NSArray<NSDictionary *> * _Nullable docTypesJSON))finished;
- (void)loadConfigurationFromString:(NSString * _Nonnull)configuration finished:(void (^ _Nonnull)(CPError * _Nullable error))finished;
- (void)login:(NSString * _Nonnull)url loginName:(NSString * _Nonnull)loginName password:(NSString * _Nonnull)password environmentFound:(void (^ _Nullable)(NSString * _Nullable notificationRegisterDeviceURL))environmentFound finished:(void (^ _Nonnull)(CPError * _Nullable error, NSArray<NSDictionary *> * _Nullable docTypesJSON))finished;
- (void)loadFieldDefinitionsForDocument:(NSString * _Nonnull)documentStateUniqueId finished:(void (^ _Nonnull)(CPError * _Nullable error, NSString * _Nullable uploadResponse))finished;
- (void)loadFieldDefinitionsForDocument:(NSString * _Nonnull)documentStateUniqueId additionalHeaders:(NSDictionary<NSString *, NSString *> * _Nonnull)additionalHeaders finished:(void (^ _Nonnull)(CPError * _Nullable error, NSString * _Nullable uploadResponse))finished;
- (void)loadFieldDefinitionsForInput:(NSString * _Nonnull)documentStateUniqueId finished:(void (^ _Nonnull)(BOOL changed, CPError * _Nullable error, NSString * _Nullable uploadResponse))finished;
- (void)loadFieldDefinitionsForInput:(NSString * _Nonnull)documentStateUniqueId additionalHeaders:(NSDictionary<NSString *, NSString *> * _Nonnull)additionalHeaders finished:(void (^ _Nonnull)(BOOL changed, CPError * _Nullable error, NSString * _Nullable uploadResponse))finished;
- (void)loadLookupValuesForKey:(NSString * _Nonnull)documentStateUniqueId keyIndex:(NSInteger)keyIndex finished:(void (^ _Nonnull)(CPError * _Nullable error, NSString * _Nullable uploadResponse))finished;
- (void)loadLookupValuesForKey:(NSString * _Nonnull)documentStateUniqueId keyIndex:(NSInteger)keyIndex additionalHeaders:(NSDictionary<NSString *, NSString *> * _Nonnull)additionalHeaders finished:(void (^ _Nonnull)(CPError * _Nullable error, NSString * _Nullable uploadResponse))finished;
- (void)loadFieldValuesForInput:(NSString * _Nonnull)documentStateUniqueId finished:(void (^ _Nonnull)(CPError * _Nullable error, NSString * _Nullable uploadResponse))finished;
- (void)loadFieldValuesForInput:(NSString * _Nonnull)documentStateUniqueId additionalHeaders:(NSDictionary<NSString *, NSString *> * _Nonnull)additionalHeaders finished:(void (^ _Nonnull)(CPError * _Nullable error, NSString * _Nullable uploadResponse))finished;
- (void)validateDocumentFields:(NSString * _Nonnull)documentStateUniqueId checkRequiredFields:(BOOL)checkRequiredFields finished:(void (^ _Nonnull)(CPError * _Nullable error, NSString * _Nullable uploadResponse, NSArray<FieldMessage *> * _Nullable fields))finished;
- (void)validateDocumentFields:(NSString * _Nonnull)documentStateUniqueId additionalHeaders:(NSDictionary<NSString *, NSString *> * _Nonnull)additionalHeaders checkRequiredFields:(BOOL)checkRequiredFields finished:(void (^ _Nonnull)(CPError * _Nullable error, NSString * _Nullable uploadResponse, NSArray<FieldMessage *> * _Nullable fields))finished;
- (void)upload:(NSString * _Nonnull)documentStateUniqueId allowCellularData:(BOOL)allowCellularData finished:(void (^ _Nullable)(CPError * _Nullable error, NSDictionary * _Nullable uploadResponseJSON))finished;
- (void)upload:(NSString * _Nonnull)documentStateUniqueId progressHandler:(void (^ _Nullable)(float progress))progressHandler finished:(void (^ _Nullable)(CPError * _Nullable error, NSDictionary * _Nullable uploadResponseJSON))finished;
- (void)upload:(NSString * _Nonnull)documentStateUniqueId additionalHeaders:(NSDictionary<NSString *, NSString *> * _Nonnull)additionalHeaders progressHandler:(void (^ _Nullable)(float progress))progressHandler finished:(void (^ _Nullable)(CPError * _Nullable error, NSDictionary * _Nullable uploadResponseJSON))finished;
- (void)upload:(NSString * _Nonnull)documentStateUniqueId additionalHeaders:(NSDictionary<NSString *, NSString *> * _Nonnull)additionalHeaders allowCellularData:(BOOL)allowCellularData progressHandler:(void (^ _Nullable)(float progress))progressHandler finished:(void (^ _Nullable)(CPError * _Nullable error, NSDictionary * _Nullable uploadResponseJSON))finished;
- (void)uploadPDF:(NSString * _Nonnull)pdfFilePath documentStateUniqueId:(NSString * _Nonnull)documentStateUniqueId additionalHeaders:(NSDictionary<NSString *, NSString *> * _Nonnull)additionalHeaders allowCellularData:(BOOL)allowCellularData progressHandler:(void (^ _Nullable)(float progress))progressHandler finished:(void (^ _Nullable)(CPError * _Nullable error, NSDictionary * _Nullable uploadResponseJSON))finished;
- (void)cancelUpload:(NSString * _Nonnull)notificationUniqueId;
@end

@class LookupValue;

SWIFT_CLASS("_TtC17MobileCapture2SDK15FieldDefinition")
@interface FieldDefinition : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable datatype;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable displayName;
@property (nonatomic, readonly, copy) NSString * _Nullable defaultValue;
@property (nonatomic, readonly, copy) NSString * _Nullable serverLookupKey;
@property (nonatomic, readonly, copy) NSArray<LookupValue *> * _Null_unspecified lookupValues;
@end


SWIFT_CLASS("_TtC17MobileCapture2SDK12FieldMessage")
@interface FieldMessage : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable message;
@end

@class UIView;
@protocol UIViewControllerTransitionCoordinator;
@protocol UIViewControllerAnimatedTransitioning;
@class UIScrollView;

SWIFT_CLASS("_TtC17MobileCapture2SDK11ImageViewer")
@interface ImageViewer : UIViewController <UIScrollViewDelegate, UIViewControllerTransitioningDelegate>

/// LIFE CYCLE BLOCKS Executed right before the image animation into its final position starts.
@property (nonatomic, copy) void (^ _Nullable showInitiationBlock)(void);

/// Executed as the last step after all the show animations.
@property (nonatomic, copy) void (^ _Nullable showCompletionBlock)(void);

/// Executed as the first step before the button's close action starts.
@property (nonatomic, copy) void (^ _Nullable closeButtonActionInitiationBlock)(void);

/// Executed as the last step for close button's close action.
@property (nonatomic, copy) void (^ _Nullable closeButtonActionCompletionBlock)(void);

/// Executed as the first step for swipe to dismiss action.
@property (nonatomic, copy) void (^ _Nullable swipeToDismissInitiationBlock)(void);

/// Executed as the last step for swipe to dismiss action.
@property (nonatomic, copy) void (^ _Nullable swipeToDismissCompletionBlock)(void);

/// Executed as the last step when the ImageViewer is dismissed (either via the close button, or swipe)
@property (nonatomic, copy) void (^ _Nullable dismissCompletionBlock)(void);
- (nonnull instancetype)initWithClientConnector:(ClientConnector * _Nonnull)clientConnector documentStateUniqueId:(NSString * _Nullable)documentStateUniqueId pageIndex:(NSInteger)pageIndex displacedView:(UIView * _Nonnull)displacedView imageSize:(CGSize)imageSize;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (void)viewWillLayoutSubviews;
- (void)loadView;
- (void)viewDidLoad;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed;
- (UIView * _Nullable)viewForZoomingInScrollView:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidZoom:(UIScrollView * _Nonnull)scrollView;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSString *, id> * _Nullable)change context:(void * _Null_unspecified)context;
@end


SWIFT_CLASS("_TtC17MobileCapture2SDK11LookupValue")
@interface LookupValue : NSObject
@property (nonatomic, copy) NSString * _Nullable value;
@property (nonatomic, copy) NSString * _Nullable displayValue;
@end


@interface NSDate (SWIFT_EXTENSION(MobileCapture2SDK))
+ (NSString * _Nonnull)ISOStringFromDate:(NSDate * _Nonnull)date;
+ (NSDate * _Nonnull)dateFromISOString:(NSString * _Nonnull)string;
@end


@interface NSURLSession (SWIFT_EXTENSION(MobileCapture2SDK))
@end


SWIFT_CLASS("_TtC17MobileCapture2SDK12Notification")
@interface Notification : NSObject
@property (nonatomic, readonly, copy) NSString * _Null_unspecified uniqueId;
@property (nonatomic, readonly, strong) NSDate * _Null_unspecified createdDateTime;
@property (nonatomic, readonly, copy) NSString * _Nullable title;
@property (nonatomic, readonly, copy) NSString * _Nullable longDescription;
@property (nonatomic, readonly, strong) NSDate * _Null_unspecified displayDateTime;
@property (nonatomic, readonly, copy) NSString * _Nullable error;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified documentStateUniqueId;
@end


@interface UIImage (SWIFT_EXTENSION(MobileCapture2SDK))
- (UIImage * _Nonnull)imageRotatedByDegrees:(CGFloat)degrees flip:(BOOL)flip;
@end


@interface UIViewController (SWIFT_EXTENSION(MobileCapture2SDK))
- (void)presentImageViewer:(ImageViewer * _Nonnull)imageViewer completion:(void (^ _Nullable)(void))completion;
@end

@class NSURL;

SWIFT_CLASS("_TtC17MobileCapture2SDK7WebData")
@interface WebData : NSObject
@property (nonatomic, strong) NSURL * _Null_unspecified returnUrl;
@property (nonatomic, copy) NSString * _Null_unspecified configurationUniqueId;
@property (nonatomic, copy) NSString * _Null_unspecified captureUniqueId;
@property (nonatomic, copy) NSString * _Nullable sessionId;
@property (nonatomic, copy) NSString * _Nullable userIdentifier;
@property (nonatomic, copy) NSString * _Nullable customData;
@property (nonatomic, copy) NSString * _Nullable documentName;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nullable fields;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
